// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clinica_Odontologica.API.Migrations
{
    [DbContext(typeof(Clinica_OdontologicaAPIContext))]
    partial class Clinica_OdontologicaAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinica_odontologia.Models01.Citas", b =>
                {
                    b.Property<int>("Id_cita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_cita"));

                    b.Property<string>("Estado_cita")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_cita");

                    b.Property<DateTime>("Fecha_cita")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_cita");

                    b.Property<int>("IdConsultorio")
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    b.Property<int>("IdOdontologo")
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("motivo");

                    b.Property<int?>("pacicienteIdPaciente")
                        .HasColumnType("integer");

                    b.HasKey("Id_cita");

                    b.HasIndex("IdConsultorio");

                    b.HasIndex("IdOdontologo");

                    b.HasIndex("pacicienteIdPaciente");

                    b.ToTable("Cita", "public");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Consultorio", b =>
                {
                    b.Property<int>("IdConsultorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsultorio"));

                    b.Property<string>("EquipamientoPrincipal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("equipamiento_principal");

                    b.Property<string>("NumeroSala")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_sala");

                    b.Property<int>("Piso")
                        .HasColumnType("integer")
                        .HasColumnName("piso");

                    b.HasKey("IdConsultorio");

                    b.ToTable("consultorios");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Detallescita", b =>
                {
                    b.Property<int>("IdDetallecita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetallecita"));

                    b.Property<double>("Costo_aplicado")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("costo_aplicado");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<int>("IdTratimiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observaciones");

                    b.Property<int?>("TratamientoIdTratamiento")
                        .HasColumnType("integer");

                    b.HasKey("IdDetallecita");

                    b.HasIndex("IdCita");

                    b.HasIndex("TratamientoIdTratamiento");

                    b.ToTable("detallecita");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_especialidad");

                    b.HasKey("IdEspecialidad");

                    b.ToTable("especialidades", "public");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Facturas", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_facturas");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<string>("Estado_pago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("Fecha_emision")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("impuestos");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdCita");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.HistorialMedico", b =>
                {
                    b.Property<int>("idHistorialMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_historial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idHistorialMedico"));

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alergias");

                    b.Property<string>("Enfermedades_previas")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("enfermedades_previas");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("Tipo_sangre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tipo_sangre");

                    b.HasKey("idHistorialMedico");

                    b.HasIndex("IdPaciente");

                    b.ToTable("historialesmedico");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Odontologo", b =>
                {
                    b.Property<int>("IdOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOdontologo"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellidos");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("Registro_medico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registro_medico");

                    b.HasKey("IdOdontologo");

                    b.HasIndex("IdEspecialidad");

                    b.ToTable("odontologos");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPaciente");

                    b.ToTable("pacientes", "public");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Receta", b =>
                {
                    b.Property<int>("IdReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_receta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReceta"));

                    b.Property<DateTime>("Fecha_emision")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<string>("Indicaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("indicaciones");

                    b.HasKey("IdReceta");

                    b.HasIndex("IdCita");

                    b.ToTable("recetas");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTratamiento"));

                    b.Property<decimal>("CostoBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costo_base");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_estimada_minutos");

                    b.Property<string>("NombreTratamiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_tratamiento");

                    b.HasKey("IdTratamiento");

                    b.ToTable("tratamientos");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Citas", b =>
                {
                    b.HasOne("Clinica_odontologia.Models01.Consultorio", "consultorio")
                        .WithMany()
                        .HasForeignKey("IdConsultorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica_odontologia.Models01.Odontologo", "odontologo")
                        .WithMany()
                        .HasForeignKey("IdOdontologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica_odontologia.Models01.Paciente", "paciciente")
                        .WithMany()
                        .HasForeignKey("pacicienteIdPaciente");

                    b.Navigation("consultorio");

                    b.Navigation("odontologo");

                    b.Navigation("paciciente");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Detallescita", b =>
                {
                    b.HasOne("Clinica_odontologia.Models01.Citas", "citas")
                        .WithMany()
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica_odontologia.Models01.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("TratamientoIdTratamiento");

                    b.Navigation("Tratamiento");

                    b.Navigation("citas");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Facturas", b =>
                {
                    b.HasOne("Clinica_odontologia.Models01.Citas", "citas")
                        .WithMany()
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("citas");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.HistorialMedico", b =>
                {
                    b.HasOne("Clinica_odontologia.Models01.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Odontologo", b =>
                {
                    b.HasOne("Clinica_odontologia.Models01.Especialidad", "especialidad")
                        .WithMany()
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("especialidad");
                });

            modelBuilder.Entity("Clinica_odontologia.Models01.Receta", b =>
                {
                    b.HasOne("Clinica_odontologia.Models01.Citas", "citas")
                        .WithMany()
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("citas");
                });
#pragma warning restore 612, 618
        }
    }
}
